# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 源数据源
      suanfa:
        url: jdbc:mysql://221.231.13.230:42264/suanfa?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # 目标数据源
      resdev:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://221.231.13.230:42264/resource_pool_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # 目标数据源
      res:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://221.231.13.230:42264/resource_pool?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

mybatis-plus:
  # 枚举包扫描 支持通配符 * 或者 ; 分隔
  type-enums-package: com.smartinsight.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/other/*.xml

server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8001
